import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'package:match_three/levels.dart';
import 'package:match_three/match_three.dart';

// Uses only visible pieces and outstanding goals, never future refills.
// Run from packages/match_three: dart run tool/calibrate_moves.dart
void main() {
  final limits = <int>[];
  final report = <Map<String, Object>>[];
  for (var index = 0; index < sweetLevels.length; index++) {
    final counts = <int>[];
    for (var trial = 0; trial < 30; trial++) {
      final random = Random(index * 1009 + trial);
      final game = sweetLevels[index].create(relaxed: true);
      while (!game.won && game.state.moves < 1000) {
        final state = game.state;
        final options = <({int a, int b, double score})>[];
        for (var a = 0; a < 49; a++) {
          for (final b in [a + 1, a + 7]) {
            if (!MatchThree.adjacent(a, b)) continue;
            final board = state.board.toList();
            final piece = board[a];
            board[a] = board[b];
            board[b] = piece;
            final cells = MatchThree.matches(board);
            final rainbow =
                board[a]!.special == Special.color ||
                board[b]!.special == Special.color;
            if (cells.isEmpty && !rainbow) continue;
            if (rainbow) {
              final type = board[a]!.special == Special.color
                  ? board[b]!.type
                  : board[a]!.type;
              cells.addAll([a, b]);
              for (var i = 0; i < 49; i++) {
                if (board[i]!.type == type) cells.add(i);
              }
            }
            final collected = List.filled(game.typeCount, 0);
            for (final i in cells) {
              collected[board[i]!.type]++;
            }
            var score = cells.length * .15;
            for (var t = 0; t < collected.length; t++) {
              score += min(
                collected[t],
                max(0, game.targets[t] - state.collected[t]),
              );
            }
            // Half the players favor larger matches that can create specials.
            if (trial.isEven &&
                game.specials != SpecialRules.none &&
                cells.length >= 4)
              score += 3;
            options.add((a: a, b: b, score: score + random.nextDouble()));
          }
        }
        options.sort((a, b) => b.score.compareTo(a.score));
        // Three mistake rates diversify trajectories on the fixed seed.
        final mistakeRate = [0.1, 0.25, 0.4][trial % 3];
        final chosen =
            options[random.nextDouble() < mistakeRate
                ? random.nextInt(options.length)
                : 0];
        game.swap(chosen.a, chosen.b);
      }
      if (!game.won)
        throw StateError('Level ${index + 1} exceeded simulation cap');
      counts.add(game.state.moves);
    }
    counts.sort();
    final number = index + 1;
    final introduction =
        number <= 5 ||
        [
          16,
          31,
          ...sweetUnlockLevels.skip(5),
        ].any((unlock) => number >= unlock && number < unlock + 3);
    final percentile = introduction || number % 5 == 0 ? .9 : .8;
    final baseline = counts[(counts.length * percentile).ceil() - 1];
    final limit = (baseline + max(2, (baseline * .1).ceil())).toInt();
    limits.add(limit);
    report.add({
      'level': number,
      'min': counts.first,
      'median': counts[counts.length ~/ 2],
      'max': counts.last,
      'limit': limit,
      'completedWithinLimit': counts.where((n) => n <= limit).length,
      'trials': counts.length,
    });
    stdout.writeln('Level $number: $limit moves');
  }
  File('lib/move_limits.dart').writeAsStringSync(
    '// Generated by tool/calibrate_moves.dart; provisional until human playtesting.\n'
    'const campaignMoveLimits = <int>[\n'
    '${limits.map((n) => '  $n,').join('\n')}\n];\n',
  );
  File('tool/move_calibration.json').writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(report)}\n',
  );
}
